options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-west3-docker.pkg.dev/$PROJECT_ID/signed-urls-caching/imgproxy:latest', '.' ]
images:
  - 'europe-west3-docker.pkg.dev/$PROJECT_ID/signed-urls-caching/imgproxy:latest'